version: 2

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/xdagiz/xytz
  mod: mod

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/xdagiz/xytz/internal/version.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "xytz-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  header: |
    ## Installation

    ```bash
    # Binary download
    curl -fsSL https://raw.githubusercontent.com/xdagiz/xytz/main/install.sh | bash

    # Or via Go
    go install github.com/xdagiz/xytz@latest

    # Arch Linux (AUR)
    yay -S xytz-bin
    ```

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

homebrew_casks:
  - name: xytz
    repository:
      owner: xdagiz
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/xdagiz/xytz"
    description: "a beautiful TUI YouTube Downloader"
  - dependencies:
      - formula: yt-dlp
      - formula: ffmpeg

aurs:
  - homepage: "https://github.com/xdagiz/xytz"
    description: "a beautiful TUI YouTube Downloader"
    maintainers:
      - "Dagmawi Ali <xdagizjr2112 at gmail dot com>"
    contributors:
      - "Dagmawi Ali <xdagizjr2112 at gmail dot com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/xytz-bin.git"
    depends:
      - yt-dlp
      - ffmpeg
    optdepends:
      - "mpv: for playing videos"

scoops:
  - name: xytz
    directory: bucket
    homepage: "https://github.com/xdagiz/xytz"
    description: "a beautiful TUI YouTube Downloader"
    license: MIT
    depends: ["yt-dlp", "ffmpeg"]
    repository:
      owner: xdagiz
      name: scoop-bucket
      token: "{{ .Env.SCOOP_TOKEN }}"
